# Generated by Django 4.1.5 on 2023-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=20)),
                ('field_2', models.CharField(max_length=20)),
                ('field_3', models.CharField(max_length=20)),
            ],
        ),
    ]
