# Generated by Django 4.1.5 on 2023-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_anton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anton',
            name='field_3',
            field=models.IntegerField(),
        ),
    ]
