# Generated by Django 4.1.5 on 2023-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_anton_field_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='anton',
            name='field_4',
            field=models.BooleanField(default=False),
        ),
    ]
