# Generated by Django 4.1.5 on 2023-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joind_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
