# Generated by Django 4.1.5 on 2023-01-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_joind_date_alter_member_married_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joind_date',
            new_name='joined_date',
        ),
    ]
